ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure("2") do |config|
  config.vm.box = "generic/freebsd12"
  config.vm.define :freebsd12
  config.vm.hostname = "freebsd12"

  config.vm.box_download_insecure = true
  # Set freebsd shell
  config.ssh.shell = "sh"

  config.vm.base_mac = "080027D14C66"

  # config.vm.network "public_network", type: "dhcp"
  config.vm.network "private_network", type: "dhcp"
  config.vm.network "forwarded_port", guest: 80, host: 8182

  config.vm.provider "virtualbox" do |vb|
  #   vb.gui = true
     vb.memory = "1024"
     vb.cpus = "1"
     vb.customize ["modifyvm", :id, "--audio", "none"]
    #vb.customize ["sharedfolder", "add", :id, "--name", "vagrant", "--hostpath", "/home/user/tmp/share", "--automount" ]
  end

  config.vm.provision "shell", inline: <<-SHELL

    # install pkg's
    env ASSUME_ALWAYS_YES=YES /usr/sbin/pkg install openssl apache24 mysql56-server;
    env ASSUME_ALWAYS_YES=YES /usr/sbin/pkg install mod_php72 php72 php72-zip php72-extensions php72-mbstring php72-openssl php72-mysqli php72-curl php72-soap php72-pdo_mysql php72-mysqli php72-gd php72-pecl-xdebug php72-curl php72-xml php72-soap php72-pecl-mcrypt php72-zlib;
    env ASSUME_ALWAYS_YES=YES /usr/sbin/pkg install wkhtmltopdf node npm git mtr vim tmux mc;
    pkg clean -a;

    # Copy php ini file
    cp /usr/local/etc/php.ini-development /usr/local/etc/php.ini;

    # install composer
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    php composer-setup.php --version=1.3.1;
    php -r "unlink('composer-setup.php');"
    mv composer.phar /usr/local/bin/composer;

    echo "
    <IfModule dir_module>
        DirectoryIndex app.php index.php index.html
        <FilesMatch "\.php$">
            SetHandler application/x-httpd-php
        </FilesMatch>
        <FilesMatch "\.phps$">
            SetHandler application/x-httpd-php-source
        </FilesMatch>
    </IfModule>" >> /usr/local/etc/apache24/Includes/php-config.conf;

    echo "
    <VirtualHost *:80>
        ServerName project.dev
        DocumentRoot /usr/local/www/apache24/data/public
        <Directory /usr/local/www/apache24/data/public >
            Options -Indexes +FollowSymLinks +MultiViews
            AllowOverride All
            Require all granted
        </Directory>
        ErrorLog /var/log/project.log
        LogLevel warn
        CustomLog /var/log/project-access.log combined
    </VirtualHost> " >> /usr/local/etc/apache24/Includes/default-site.conf

    echo "
  [xdebug]
  xdebug.remote_port=9000
  xdebug.remote_enable=true
  xdebug.remote_connect_back=true
  xdebug.remote_autostart=on
  xdebug.remote_host=10.0.2.1
  xdebug.max_nesting_level=1000
  xdebug.idekey=PHPSTORM
    " >> /usr/local/etc/php.ini

    sed -e "s|#LoadModule rewrite_module|LoadModule rewrite_module|" /usr/local/etc/apache24/httpd.conf>/usr/local/etc/apache24/httpd.bak;
    mv /usr/local/etc/apache24/httpd.bak /usr/local/etc/apache24/httpd.conf;

    # For NFS
    sysrc rpc_lockd_enable=yes;
    sysrc rpc_statd_enable=yes;

    # start apache24
    sysrc apache24_enable=yes;
    service apache24 start;

    # start database server
    sysrc mysql_enable=yes;
    service mysql-server start;
    mysqladmin -u root password 'root'
    mysql -uroot -proot -e "create database opencart";

  SHELL

  config.vm.synced_folder "/home/dima/work/vagrants/freebsd12/data", "/usr/local/www/apache24/data/public", 
  :nfs => true, id: "vagrant-root", :mount_options => ['rw', 'vers=3', 'tcp', 'actimeo=2']
end
