Vagrant.configure("2") do |config|
  config.vm.box = "generic/gentoo"
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
     vb.cpus = "1"
     vb.customize ["modifyvm", :id, "--audio", "none"]
    #vb.customize ["sharedfolder", "add", :id, "--name", "vagrant", "--hostpath", "/home/user/tmp/share", "--automount" ]
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo emerge app-misc/tmux app-misc/mc net-analyzer/mtr sys-process/htop
    sudo emerge media-gfx/wkhtmltopdf dev-vcs/git dev-db/redis

    #echo "PHP_TARGETS=\"php7-2\"" | sudo tee -a /etc/portage/make.conf
    echo "USE_PHP=\"zip zlib mysql mysqli pdo phar session\"" | sudo tee -a /etc/portage/make.conf
    sudo emerge dev-lang/php dev-php/xdebug

    #eselect php list cli
    sudo emerge www-servers/apache
    echo "USE=\"apache2\"" | sudo tee -a /etc/portage/make.conf
    sudo emerge --changed-use --deep @world

    sed -e "s|APACHE2_OPTS=\"|APACHE2_OPTS=\"-D PHP|" /etc/conf.d/apache2 | sudo tee /etc/conf.d/apache2;
    #sudo chown apache:apache /var/www/sitename

    sudo rc-update add apache2 default
    sudo /etc/init.d/apache2 start
    #netstat -tulpen | grep apache

    sudo emerge emerge dev-db/mysql
    sudo /etc/init.d/mysql start
    sudo rc-update add mysql default
    /usr/bin/mysqladmin -u root -h localhost password 'root'

  SHELL
end
