Vagrant.configure("2") do |config|
  config.vm.box = "generic/gentoo"
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
     vb.cpus = "1"
     vb.customize ["modifyvm", :id, "--audio", "none"]
    #vb.customize ["sharedfolder", "add", :id, "--name", "vagrant", "--hostpath", "/home/user/tmp/share", "--automount" ]
  end

  config.vm.provision "shell", inline: <<-SHELL
    emerge --sync
    emerge --update world
    emerge app-misc/tmux app-misc/mc net-analyzer/mtr sys-process/htop
    # emerge media-gfx/wkhtmltopdf
    emerge dev-vcs/git dev-db/redis

    #echo "PHP_TARGETS=\"php7-2\"" | tee -a /etc/portage/make.conf
    echo "USE_PHP=\"cli apache2 zip zlib mysqli pdo phar session\"" | tee -a /etc/portage/make.conf
    emerge dev-lang/php dev-php/xdebug

    #eselect php list cli
    emerge www-servers/apache
    echo "USE=\"apache2\"" | tee -a /etc/portage/make.conf
    emerge --changed-use --deep @world

    sed -e "s|APACHE2_OPTS=\"|APACHE2_OPTS=\"-D PHP -D DEFAULT_VHOST -D INFO -D LANGUAGE -D SSL -D SSL_DEFAULT_VHOST|" /etc/conf.d/apache2 | tee /etc/conf.d/apache2;
    #chown apache:apache /var/www/sitename

    rc-update add apache2 default
    /etc/init.d/apache2 restart
    netstat -tulpen | grep apache

    emerge emerge dev-db/mysql
    /etc/init.d/mysql start
    rc-update add mysql default
    /usr/bin/mysqladmin -u root -h localhost password 'root'

  SHELL
end
