Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
     vb.memory = "1024"
  end
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y sysstat htop apg iotop openssl curl vim wget unzip bc zip mc
    apt-get install -y git subversion redis-tools
    apt-get install -y apache2
    apt-get install -y mysql-server redis-server
    apt-get install -y imagemagick wkhtmltopdf sendmail libssl-dev build-essential ffmpeg mailutils apache2 libapache2-mod-xsendfile
    apt-get install -y php libapache2-mod-php7.2 php7.2-gd php7.2-dom php7.2-curl php7.2-mysql php7.2-json php-tidy php-mbstring php-imagick php-memcached php-zip php7.2-soap php-xdebug    

    addgroup webusers
    addgroup webdata
    adduser --disabled-password --GECOS '' deploy
    adduser deploy webdata
    adduser www-data webusers

    chown -R vagrant:webusers /var/www

    sed -i 's/post_max_size = .*/post_max_size = 256M/g' /etc/php/7.*/apache2/php.ini
    sed -i 's/upload_max_filesize = .*/upload_max_filesize = 256M/g' /etc/php/7.*/apache2/php.ini
    sed --regexp-extended -i 's/^.?date.timezone =.*/date.timezone = "UTC"/g' /etc/php/7.*/apache2/php.ini
    sed --regexp-extended -i 's/^.?date.timezone =.*/date.timezone = "UTC"/g' /etc/php/7.*/cli/php.ini

    echo 'xdebug.remote_port=9000' >> /etc/php/7.*/apache2/php.ini
    echo 'xdebug.remote_enable=true' >> /etc/php/7.*/apache2/php.ini
    echo 'xdebug.remote_connect_back=true' >> /etc/php/7.*/apache2/php.ini
    echo 'xdebug.remote_autostart=on' >> /etc/php/7.*/apache2/php.ini
    echo 'xdebug.remote_host=10.0.2.1' >> /etc/php/7.*/apache2/php.ini
    echo 'xdebug.max_nesting_level=1000' >> /etc/php/7.*/apache2/php.ini
    echo 'xdebug.idekey=PHPSTORM' >> /etc/php/7.*/apache2/php.ini

    mysql -e "create user vagrant@localhost identified by '' "
    mysql -e "grant all on *.* to vagrant@localhost with grant option"

    a2enmod rewrite && a2enmod xsendfile && a2enmod expires  && a2enmod ssl && apachectl restart

    curl -Ss https://getcomposer.org/installer | php > /dev/null
    sudo mv composer.phar /usr/bin/composer

    sudo systemctl restart apache2

  SHELL

  config.vm.synced_folder "./data", "/var/www/html", group: 1002, mount_options: ["dmode=775,fmode=775"]
end
